package com.example.data.model

enum class MediaType {
    MOVIE,
    TV_SERIES
}

enum class MediaSource {
    LOCAL,
    CLOUD,
    ONLINE_STREAM
}

enum class SubtitleVerticalPosition {
    BOTTOM,
    CENTER,
    TOP
}

enum class SubtitleBackgroundStyle {
    TRANSLUCENT_BLACK,
    SOLID_BLACK,
    SHADOW_OUTLINE,
    NONE
}

data class SubtitleCue(
    val startTimeMs: Long,
    val endTimeMs: Long,
    val text: String
)

data class SubtitleStyleConfig(
    val verticalPosition: SubtitleVerticalPosition = SubtitleVerticalPosition.BOTTOM,
    val verticalOffsetDp: Int = 36, // Distance from bottom/top edge
    val fontSizeSp: Int = 18,
    val textColorHex: Long = 0xFFFFFFFF,
    val backgroundStyle: SubtitleBackgroundStyle = SubtitleBackgroundStyle.TRANSLUCENT_BLACK,
    val timingOffsetMs: Long = 0L // +/- audio sync offset
)

data class SubtitleTrack(
    val id: String,
    val label: String,
    val language: String,
    val format: String, // SRT, VTT, AUTO_AI
    val uriOrContent: String,
    val isExternal: Boolean = false,
    val isAutoGenerated: Boolean = false
)
